implement login and findByEmail methods
mate-academy/jv-oop-lesson-0 pull request #1081
Opened 2024-08-20 17:15 UTC by skotsurskiy

2024-08-20 17:46 UTC, okuzan requested changes

2024-08-20 17:46 UTC, okuzan commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        if (new UserService().findByEmail(email) != null
UserService should be a private class-level field, not an anonymous instance

2024-08-20 17:46 UTC, okuzan commented on src/main/java/mate/academy/service/AuthenticationService.java
> +                && user.getPassword().equals(new UserService().findByEmail(email).getPassword())) {
moreover, you create it twice per each method call. You should create one per each method _instance_

2024-08-20 17:46 UTC, okuzan commented on src/main/java/mate/academy/service/AuthenticationService.java
>          return false;
try to rewrite your solution without using true/false boolean literals 😉

2024-08-21 11:07 UTC, okuzan requested changes
almost done

2024-08-21 11:07 UTC, okuzan commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        User user = new User(email, password);
```suggestion
```
use values directly

2024-08-21 11:07 UTC, okuzan commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        User checkuser = userService.findByEmail(email);
```suggestion
        User user= userService.findByEmail(email);
```

2024-08-21 13:32 UTC, Elena-Bruyako approved these changes

2025-09-27 08:08 UTC, closed without merging