Hw oop 0
mate-academy/jv-oop-lesson-0 pull request #561
Opened 2023-06-10 13:59 UTC by Skarbey

Implemented requested methods make it possible to find user by email and check successful login or not.
 Code passed through mvn clean package

2023-06-14 05:07 UTC, KseniiaMakarova requested changes

2023-06-14 05:07 UTC, KseniiaMakarova commented on src/main/java/mate/academy/service/UserService.java
> +    public static User findByEmail(String email) {
```suggestion
    public User findByEmail(String email) {
```

2023-06-14 05:07 UTC, KseniiaMakarova commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        if (UserService.findByEmail(emailEntered) == null) {
create an object and call this method on an object

2023-06-14 05:07 UTC, KseniiaMakarova commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        }
```suggestion
            return false;
        } 
        return passwordEntered.equals(user.getPassword());
```

2023-06-14 05:07 UTC, KseniiaMakarova commented on src/main/java/mate/academy/service/UserService.java
> +        for (User oneInAllUsers : users) {
```suggestion
        for (User user : users) {
```

2023-06-14 10:10 UTC, KseniiaMakarova requested changes

2023-06-14 10:10 UTC, KseniiaMakarova commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        }
```suggestion
        } 
        return passwordEntered.equals(findedUser.getPassword());
```
we don't need else after return

2023-06-17 09:58 UTC, Skarbey commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        }
Thanks for advice. I fixed it

2023-11-23 07:51 UTC, closed without merging