Did all tasks, implemented login() and findByEmail() methods
mate-academy/jv-oop-lesson-0 pull request #761
Opened 2023-10-28 17:39 UTC by Trayvor

2023-10-29 10:56 UTC, Ivan95kos requested changes

2023-10-29 10:56 UTC, Ivan95kos commented on src/main/java/mate/academy/service/UserService.java
> +    public static final User[] users = new User[] {
the field must be the private, revert it
```suggestion
    private static final User[] users = new User[] {
```

2023-10-29 10:56 UTC, Ivan95kos commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        UserService userService = new UserService();
`UserService` must be a class field
```suggestion
```

2023-10-29 10:56 UTC, Ivan95kos commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        }
use the method `findByEmail` instead of `loop`

2023-10-30 12:19 UTC, okuzan approved these changes

2024-11-10 17:32 UTC, closed without merging