oop first solution
mate-academy/jv-oop-lesson-0 pull request #793
Opened 2023-11-10 20:17 UTC by KoderNL

2023-11-11 10:26 UTC, Sanderfuck reviewed
![image](https://github.com/mate-academy/jv-oop-lesson-0/assets/63095184/21edfa11-a207-49ad-bdb5-486d2ff16bba)
Fix this

2023-11-11 10:26 UTC, Sanderfuck commented on src/main/java/mate/academy/service/AuthenticationService.java
>          return false;
userService.findByEmail(email) - you can save it to variable and use it many times

2023-11-11 10:27 UTC, Sanderfuck requested changes
Fix problem with checks in github

2023-11-11 11:01 UTC, KoderNL commented
> ![image](https://user-images.githubusercontent.com/63095184/282236217-21edfa11-a207-49ad-bdb5-486d2ff16bba.png) Fix this

я не розумію в чому тут проблема та як я можу її пофіксити

2023-11-12 17:50 UTC, KoderNL commented
I'm already fixed last problem and change some code with your advice, you can check please

2023-11-13 11:02 UTC, Sanderfuck requested changes

2023-11-13 11:02 UTC, Sanderfuck commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        }
You already have user field, why do you duplicate code of user inside if(......)?
You can simplify it to one line in return

2023-11-13 13:00 UTC, kerrrusha approved these changes

2023-11-13 13:00 UTC, kerrrusha commented on src/main/java/mate/academy/service/AuthenticationService.java
>          return false;
```suggestion
        return user != null && user.getPassword().equals(password);
```

2023-11-13 13:00 UTC, kerrrusha commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        UserService userService = new UserService();
services should be `private final` class-level fields
```suggestion
     */
    private final UserService userService = new UserService();
    
    public boolean login(String email, String password) {
```

2026-01-12 20:26 UTC, closed without merging