fixed AuthenticationService and UserService methods
mate-academy/jv-oop-lesson-0 pull request #849
Opened 2023-12-11 16:47 UTC by kvjohnny

2023-12-12 09:38 UTC, Sanderfuck requested changes

2023-12-12 09:38 UTC, Sanderfuck commented on src/main/java/mate/academy/service/AuthenticationService.java
> +                && findByEmail(email).getPassword().equals(password);
You duplicate 2 times - findByEmail(email), save it to variable

2023-12-12 09:38 UTC, Sanderfuck commented on src/main/java/mate/academy/service/AuthenticationService.java
> +public class AuthenticationService extends UserService {
You can`t extends from UserService

2023-12-12 19:47 UTC, okuzan requested changes

2023-12-12 19:47 UTC, okuzan commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        User byEmail = userService.findByEmail(email);
```suggestion
        User user = userService.findByEmail(email);
```
bad naming, doesn't tell us what it stores

2023-12-13 09:11 UTC, Sanderfuck requested changes

2023-12-13 09:11 UTC, Sanderfuck commented on src/main/java/mate/academy/model/User.java
> +    private final String password;
You don`t need it

2023-12-13 09:11 UTC, Sanderfuck commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        User findByEmail = userService.findByEmail(email);
Change name "user" instead "findByEmail", your naming not informative

2023-12-14 18:38 UTC, olekskov approved these changes
Good job

2023-12-14 19:44 UTC, kvjohnny commented
Thank you so much!

2023-12-14 19:44 UTC, closed without merging