jv-oop-lesson-0 HW solution
mate-academy/jv-oop-lesson-0 pull request #905
Opened 2024-01-14 12:15 UTC by luk14n

2024-01-14 13:28 UTC, MentorMA requested changes

2024-01-14 13:28 UTC, MentorMA commented on src/main/java/mate/academy/service/AuthenticationService.java
>          return false;
Simplify this to one line in return state

2024-01-15 12:28 UTC, okuzan requested changes

2024-01-15 12:28 UTC, okuzan commented on src/main/java/mate/academy/service/AuthenticationService.java
> +                && userService.findByEmail(email).getPassword().equals(password);
save the result of a service call to a local variable and use it, instead of calling service twice 🙏

2024-01-15 13:10 UTC, okuzan approved these changes

2024-01-15 15:52 UTC, closed without merging