add new constructor
mate-academy/jv-oop-lesson-0 pull request #921
Opened 2024-01-24 20:29 UTC by mstefanchuk

2024-01-25 11:34 UTC, kozhukhovsky requested changes

2024-01-25 11:34 UTC, kozhukhovsky commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        User user = userService.findByEmail(email);
u can realize method findByEmail in user service

2024-01-25 12:03 UTC, mstefanchuk commented on src/main/java/mate/academy/service/AuthenticationService.java
> +        User user = userService.findByEmail(email);
> u should realize method findByEmail in user service

Тобто клас AuthenticationService не потрібно чипати?

2024-02-05 10:24 UTC, kozhukhovsky approved these changes

2024-04-22 16:13 UTC, closed without merging